### ISSUE TITLE
BCH test has invalid xpub corresponding to xprv key

### ISSUE THREAD

**Issue by nmarley** [GENERALBYTESCOM/bitrafael_public#33]
The file is `bitrafael-client/src/test/java/com/generalbytes/bitrafael/api/wallet/bch/WalletToolsBCHTest.java`.

In the method `getMasterPrivateKey`, the extended *private* key derived from the example mnemonic `abandon abandon abandon` with password of `password` is `xprv9s21ZrQH143K25nXfd4XuZ6d955Y7XQ7GzSrew7bEYCx1eC6JixjXoaULDjgpB4BJaLL4BmCTka4L9Jq5rxstLcXLnVkGK4tkMk8D9iv1y8`, which is correct.

But the test for the corresponding xpub key `xpub6C9nRehjbvKLDD1Rzjshv5HaTm9Q1qFnraUZ34uVtbQzgAMFffuhTxN2umR6gfjWYyf4egfQVCbRegE9gMYCwbK3rsV8Xz1LU2KAHUvNaYB` is not correct, as the correct key should be `xpub661MyMwAqRbcEZrzmebYGh3Mh6v2Wz7xeDNTTKXCnsjvtSXErGGz5btxBU7Kyfy5EwthQ5ZRhQ2wqRHU5QCESg11V8bywtkRWhZNr94AgH9`, from a couple different tests I've run.

I'm not sure if you're actually running these tests or not but if so, this would point to a bug in your code.

I would also recommend extracting these BIP39 type items to a separate library or area and only test those there, instead of together with BCH tests.

**Comment by pvyhnal-generalbytes** [comment]
Please see below hot to get the xpub you mentioned that is in our test. 
Could you please share the tests you run to get 
`xpub661MyMwAqRbcEZrzmebYGh3Mh6v2Wz7xeDNTTKXCnsjvtSXErGGz5btxBU7Kyfy5EwthQ5ZRhQ2wqRHU5QCESg11V8bywtkRWhZNr94AgH9`? Thanks 

https://iancoleman.io/bip39/ 

BIP32 Root Key:  
xprv9s21ZrQH143K25nXfd4XuZ6d955Y7XQ7GzSrew7bEYCx1eC6JixjXoaULDjgpB4BJaLL4BmCTka4L9Jq5rxstLcXLnVkGK4tkMk8D9iv1y8

Purpose: 44
Coin: 145 (BCH)
Account: 0
External / Internal: 0

Account Extended Public Key
xpub6C9nRehjbvKLDD1Rzjshv5HaTm9Q1qFnraUZ34uVtbQzgAMFffuhTxN2umR6gfjWYyf4egfQVCbRegE9gMYCwbK3rsV8Xz1LU2KAHUvNaYB

**Comment by nmarley** [comment]
Hi, the line in question is:

```java
public void getMasterPrivateKey() {
    Assert.assertEquals("xprv9s21ZrQH143K25nXfd4XuZ6d955Y7XQ7GzSrew7bEYCx1eC6JixjXoaULDjgpB4BJaLL4BmCTka4L9Jq5rxstLcXLnVkGK4tkMk8D9iv1y8", masterPrivateKey.getPRV());
    Assert.assertEquals("xpub6C9nRehjbvKLDD1Rzjshv5HaTm9Q1qFnraUZ34uVtbQzgAMFffuhTxN2umR6gfjWYyf4egfQVCbRegE9gMYCwbK3rsV8Xz1LU2KAHUvNaYB", masterPrivateKey.getPUB());
}
```

I had assumed that master.getPUB would get the master public key associated with the master private key, but instead it seems like it gets a derived key, so your code might be "correct", according to how GB intends for it to work.

But it's kinda confusing. The actual *master* pubkey associated with the *master* privkey is as I stated above. You can see this by using the BIP39 web tool you referenced, pasting in the priv key at the bottom, then switching over to the BIP32 tab and using just `m` as the BIP32 Derivation Path.

Prior to realizing this I prepared these utils to demonstrate that in both Javascript and Go: https://github.com/nmarley/hdkeytest

But I'm guessing that's not your intent w/the code, and that `getPUB()` is actually intended to return a derived key. Feel free to close this, I doubt a large code refactor is worth it at this point.

**Comment by pvyhnal-generalbytes** [comment]
Hi, thanks, our getPUB() method returns `m/44'/145'/0'`

**Comment by nmarley** [comment]
Thanks, in that case it looks like this key is correct and the library is confusing instead.
