### ISSUE TITLE
For more security spongycastle -> bouncycastle

### ISSUE THREAD

**Issue by Neustradamus** [GENERALBYTESCOM/bitrafael_public#36]
For more security, can you change old spongycastle (based on old bouncycastle) to bouncycastle?
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Neustradamus** [comment]
@generalbytes: Have you seen this ticket?

**Comment by generalbytes** [comment]
Not a priority now. Adding newer bouncy castle would require to upgrade bitcoinj, dashj libs etc.

**Comment by Neustradamus** [comment]
@generalbytes: The security is important!
Please do not close an unsolved ticket.
Thanks in advance.

**Comment by Neustradamus** [comment]
@generalbytes: Any news?

**Comment by Neustradamus** [comment]
@generalbytes: Any news?
- https://github.com/GENERALBYTESCOM/bitrafael_public/search?q=spongycastle

**Comment by Neustradamus** [comment]
@generalbytes: Can you remove old Spongy Castle code?
- https://github.com/GENERALBYTESCOM/bitrafael_public/search?q=spongycastle

And update Bouncy Castle to 1.69?
